### ISSUE TITLE
Google Cloud Storage

### ISSUE THREAD

**Issue by anandjaisy** [micronaut-projects/micronaut-eclipsestore#49]
Eclipse store already has an option to store the data in Google Cloud Firestore with below dependencies

https://docs.eclipsestore.io/manual/storage/storage-targets/blob-stores/google-cloud-firestore.html

```
<dependency>
	<groupId>org.eclipse.store</groupId>
	<artifactId>afs-googlecloud-firestore</artifactId>
	<version>1.3.2</version>
</dependency>
<dependency>
	<groupId>com.google.cloud</groupId>
	<artifactId>google-cloud-firestore</artifactId>
	<version>3.0.17</version>
</dependency>
```

Is there any planning for the Google storage file system? It will be good if we provide a google bucket storage feature.

**Comment by SimonFrauenschuh** [comment]
I've done most of the work in this [PR](https://github.com/micronaut-projects/micronaut-eclipsestore/pull/85).

If you are able to get the tests running in parallel, then I guess it will be merged soon

**Comment by anandjaisy** [comment]
@SimonFrauenschuh  does your PR also fixed the Google Cloud Firestore ??? If so can you share few code sample

**Comment by SimonFrauenschuh** [comment]
> [@SimonFrauenschuh](https://github.com/SimonFrauenschuh) does your PR also fixed the Google Cloud Firestore ??? If so can you share few code sample

Sorry, I don't have an explicit example code that I could share. But yes, this should integrate the Google Firestore option of eclipsestore into the micronaut plugin

But you could just copy the [example on the micronaut docs](https://guides.micronaut.io/latest/micronaut-eclipsestore-persitence-gradle-java.html) and replace the code from section 4.4 with the following (paste the code in you `application.yml`)
```yaml
eclipsestore:
  firestore: # Note: this will only work with my PR as dependency base or if it is merged
    storage:
      default: # Or a different name for a named bean
        logical-directory: dependencyClient
        root-class: com.example.model.Root
```

I've also added documentation in the PR but it seems like it isn't rendered in [the docs](https://micronaut-projects.github.io/micronaut-eclipsestore/1.8.0/guide/#storageTargets).


@graemerocher Sorry for pinging you but what did I miss in updating the documentation? This is what I've added [in code](https://github.com/micronaut-projects/micronaut-eclipsestore/pull/85/changes#diff-57ee70784c1eeec7313ac66a72c6e8e469571935df9b3e27b6f2a1a81567b31cR13)
